### ISSUE TITLE
Qualified majority

### ISSUE THREAD

**Issue by SmithPeder** [webkom/vote#378]
We need a way to set an election to use a **qualified majority** in some of the STV elections. As per the [new project](https://github.com/webkom/vote/projects/1), there is only **one** way of voting. This means that all elections must be conducted using STV. This is not a problem since most elections will get the same outcome as elections done today.

The only problem is elections that demand a **Qualified majority (2/3 votes)**. The implementation (as is) will always calculate a [DroopQuota](https://en.wikipedia.org/wiki/Droop_quota) as seen in the equation below.
![image](https://user-images.githubusercontent.com/23152018/102212861-2505e980-3ed6-11eb-8940-7da843814718.png)

This means an election for 1 position will always return a 50% threshold.
> Example: 100 votes, 1 position, 3 candidates => `(100/2) + 1 = 51`. Note the number of candidates will never have anything to do with the quota.

This number above will represent **§ 0.2 Alminnelig flertall**, so this can be used for all standard elections where Alminnelig flertall is required.
![image](https://user-images.githubusercontent.com/23152018/102213292-d3aa2a00-3ed6-11eb-8732-a9cff3f0454a.png)

The problem arises when votes that require Kvalifisert flertall is held
![image](https://user-images.githubusercontent.com/23152018/102213220-b6755b80-3ed6-11eb-93ea-932d3db0aabb.png)

Then the election will not go correctly, because if you propose a statute change with "Yes/No" as the answers, this will also result in a `50% droop quota`. Therefore we need to implement a `useStrict` flag on the election that overrides what quota is used. When `useStrict` is set then the quota is set as:
![image](https://user-images.githubusercontent.com/23152018/102213746-7c588980-3ed7-11eb-8c7e-7d27196f02b2.png)
This means a strict election will always return a 67% threshold.
> Example: 100 votes, 1 posistion, 3 candidates => `((2*100)/3)+1 = 67`

This number above will represent **§ 0.3 Kvalifisert flertall**

Another thing we should do is add a constraint that says a strict election only can have one seat/position here https://github.com/webkom/vote/issues/352.

**Comment by SmithPeder** [comment]
@JonasBak Any thoughts 🥇

**Comment by SmithPeder** [comment]
It will also work pretty sweet for statute changes that have many options.

 For example the 2019 Generalforsamling **Opprettelse av statutt § 10.2.3** where the proposition of creating the new statute had two suggestions.
![image](https://user-images.githubusercontent.com/23152018/102215073-7d8ab600-3ed9-11eb-90ce-4c4a07543c33.png)
When we voted for this we had to do some wired stuff where we voted for 
- **Suggestion 2 vs None vs Blank**
Then 
- **Suggestion 1 vs None vs Blank**

This could easily have been solved with a Strict STV implementation where you ranked what you wanted. Then an option would require 2/3 approval, and votes would transfer. So if you wanted 10% most and had 5% as the second preference, then your votes would transfer over and maybe the 5% would go over the threshold.

**Comment by JonasBak** [comment]
I agree that a flag is probably a nice way to go. We should probably also find a way to separate between different "cases" of elections (normal stv, "old-school vote" with yes/no/blank) to show different views in the frontend (might be weird to rank "yes", "no" and "blank"), and we could incorporate this into that "classification" with an enum-type-thing.

> It will also work pretty sweet for statute changes that have many options.

Agreed, but probably a case where HS has to present the "stv log" (not that this is our problem :upside_down_face: )

**Comment by SmithPeder** [comment]
> Agreed, but probably a case where HS has to present the "stv log"

The log is already returned and shown on the admin dashboard, so that's no problem

**Comment by SmithPeder** [comment]
> We should probably also find a way to separate between different "cases" of elections (normal stv, "old-school vote" with yes/no/blank) to show different views in the frontend (might be weird to rank "yes", "no" and "blank"),

We talked a bit about this. **Blank** will never be __rankable__.  

Either you:
- Press the blank button => `priorities = []`
- Only rank some of the options => `priorities.length < alternatives.length`


But I agree that it's kinda wired to rank two options, but I feel like that might be a minor problem. We thought about doing a frontend `switch-case` that checks how many alternatives are available, and maybe show a different GUI when there are only two options, but we are a little afraid that there will be too much "if-else" logic and the GUI will change all the time/

**Comment by JonasBak** [comment]
> We thought about doing a frontend switch-case that checks how many alternatives are available

This is where I think selecting an "election type" when creating the election could be a better solution that is easier to validate. The case with "yes", "no", "blank" is also a bit different in that while there used to be only two outcomes ("passed" with enough "yes" votes or "failed to pass" otherwise), there will now be three ("passed", "failed to pass" with enough "no" votes, or "undecided" otherwise). Might be worth showing the results in a different way. But this isn't really __qualified majority__-stuff.

**Comment by LudvigHz** [comment]
Hmm, the yes/no situation is a bit weird yeah. Since in this case no and Blank means the same thing. But doing it like that would probably cause an outrage at genfors:tm:. You could have a separate election type for these cases  I guess, where you only have yes and no as alternatives, and the possibility to only select one of them. This would cause a lot of extra, edge-case code though.

You could also make the argument where you switch out No for "Keep as is" and yes for "New option". And in this case I guess people could say that they vouch for both options, but like one more than the other, essentially keeping the ranking yes/no UI. But again, this is weird with qualified majority, since "keep as is" and unresolved is the same.

But I'm not sure what the best option is 🤔.

**Comment by SmithPeder** [comment]
We solved this with the 2/3 button in #359  and the code in #371 and #370 then force the election to use a 2/3 Majority, and disregards the number of seats.
